version: 2
# Build customization
builds:
  - main: .
    binary: armclient
    goos: [ 'darwin', 'linux', 'windows' ]
    goarch: [ 'amd64', 'arm64' ]
    ignore:
      - goos: windows
        goarch: arm64
      - goos: linux
        goarch: arm64
# Archive customization
archives:
  - id: default
    formats: [ 'tar.gz' ]
    name_template: '{{ .ProjectName }}_{{- if eq .Os "darwin" }}macOS{{ else }}{{ .Os }}{{ end }}_{{ .Arch }}'
    format_overrides:
      - goos: windows
        formats: [ 'zip' ]
    files:
      - LICENSE